/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jdbc.program;

import jdbc.service.MysqlMahasiswaService;
/**
 *
 * @author arsym
 */

/*
 * Nama file    : JFrameUtama.java
 * Deskripsi    : file program implementasi GUI pada data mahasiswa
 * Pembuat      : Yuma Hazza Yuditama
 * NIM          : 24060124120035
 * Tanggal      : 26 Mei 2026
*/

public class JFrameUtama extends javax.swing.JFrame {
    private MysqlMahasiswaService service;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JFrameUtama.class.getName());

    /**
     * Creates new form JFrameUtama
     */
    public JFrameUtama() {
        initComponents();
        
        service = new MysqlMahasiswaService(); 
        displayToGUI(); // Mengisi list otomatis saat aplikasi pertama dibuka
        
        listId.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            @Override
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                // getValueIsAdjusting() memastikan event hanya dieksekusi sekali saat klik selesai
                if (!evt.getValueIsAdjusting()) {
                    listIdValueChanged();
                }
            }
        });
        
        listNama.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            @Override
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                if (!evt.getValueIsAdjusting()) {
                    listNamaValueChanged();
                }
            }
        });
        
        this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                if (service != null) service.closeConnection();
            }
        });
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    @SuppressWarnings("unchecked")                         
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtInputNama1 = new javax.swing.JTextField();
        txtInputNama2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        listId = new javax.swing.JList<>();
        listNama = new javax.swing.JList<>();
        jButtonAmbilSemuaData = new javax.swing.JButton();
        txtInputNama = new javax.swing.JTextField();
        jButtonTambahkan = new javax.swing.JButton();
        txtIdEdit = new javax.swing.JTextField();
        txtNamaEdit = new javax.swing.JTextField();
        jButtonEdit = new javax.swing.JButton();
        txtIdHapus = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jButtonHapus = new javax.swing.JButton();
        jButtonResetIndeks = new javax.swing.JButton();
        lblStatusIndeks = new javax.swing.JLabel();

        jLabel5.setText("jLabel5");

        jLabel6.setText("jLabel6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(listId);

        jLabel1.setText("ID");

        jScrollPane2.setViewportView(listNama);

        jLabel2.setText("NAMA");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("KELOLA DATA MAHASISWA");
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jButtonAmbilSemuaData.setText("Ambil Semua Data");
        jButtonAmbilSemuaData.addActionListener(this::jButtonAmbilSemuaDataActionPerformed);

        jLabel4.setText("nama:");

        jButtonTambahkan.setText("Tambahkan");
        jButtonTambahkan.addActionListener(this::jButtonTambahkanActionPerformed);

        txtIdEdit.addActionListener(this::txtIdEditActionPerformed);

        txtNamaEdit.addActionListener(this::txtNamaEditActionPerformed);

        jButtonEdit.setText("Edit");
        jButtonEdit.addActionListener(this::jButtonEditActionPerformed);

        jButtonHapus.setText("Hapus");
        jButtonHapus.addActionListener(this::jButtonHapusActionPerformed);

        jButtonResetIndeks.setText("Reset Indeks");
        jButtonResetIndeks.addActionListener(this::jButtonResetIndeksActionPerformed);

        lblStatusIndeks.setText("index di reset ke 0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtInputNama)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3)
                            .addComponent(jButtonAmbilSemuaData)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonTambahkan)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtIdHapus, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                    .addComponent(txtIdEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNamaEdit)
                                    .addComponent(jTextField5, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButtonHapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonResetIndeks, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblStatusIndeks, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)))
                        .addGap(0, 9, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                            .addComponent(jScrollPane1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonAmbilSemuaData)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtInputNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonTambahkan)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtIdEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNamaEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonEdit))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtIdHapus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonHapus))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonResetIndeks)
                            .addComponent(lblStatusIndeks))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    private void txtIdEditActionPerformed(java.awt.event.ActionEvent evt) {}                                         

    private void jButtonAmbilSemuaDataActionPerformed(java.awt.event.ActionEvent evt) {                                                      
        displayToGUI();
    }                                                     

    private void jButtonTambahkanActionPerformed(java.awt.event.ActionEvent evt) {                                                         String inputNama = txtInputNama.getText().trim();
        if (!inputNama.isEmpty()) {
            jdbc.model.Mahasiswa mhsAdd = new jdbc.model.Mahasiswa(inputNama);
            service.add(mhsAdd); // Kirim data ke DB
        
            txtInputNama.setText(""); // Kosongkan field input
            displayToGUI();           // Refresh tampilan layar
        }
    }                                                

    private void jButtonEditActionPerformed(java.awt.event.ActionEvent evt) {                                            
        String strId = txtIdEdit.getText().trim();
        String namaBaru = txtNamaEdit.getText().trim();
    
        if (!strId.isEmpty() && !namaBaru.isEmpty()) {
            int id = Integer.parseInt(strId);
            jdbc.model.Mahasiswa mhsUpdate = new jdbc.model.Mahasiswa(id, namaBaru);
            service.update(mhsUpdate); // Update data di DB
        
            txtNamaEdit.setText("");   // Kosongkan inputan
            displayToGUI();          // Refresh tampilan layar
         }
    }                                           

    private void jButtonHapusActionPerformed(java.awt.event.ActionEvent evt) {                                             
        String strId = txtIdHapus.getText().trim();
        if (!strId.isEmpty()) {
            int id = Integer.parseInt(strId);
            service.delete(id); // Hapus data di DB
        
            // KOSONGKAN FIELD SETELAH HAPUS
            txtIdHapus.setText(""); 
            jTextField5.setText(""); // Mengosongkan field nama pada baris hapus
        
            // Opsional: kosongkan juga field edit agar tidak menyisa data lama
            txtIdEdit.setText("");
            txtNamaEdit.setText("");
        
        displayToGUI();         // Refresh tampilan layar
        }
    }                                            

    private void jButtonResetIndeksActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        service.indexReset(); // Mengosongkan tabel & mereset auto-increment via TRUNCATE
        lblStatusIndeks.setText("Index di reset ke 0"); // Mengubah teks label di samping tombol
        displayToGUI(); // Layar otomatis kosong karena tabel sudah dibersihkan
    }                                                  

    private void txtNamaEditActionPerformed(java.awt.event.ActionEvent evt) {}                                           

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JFrameUtama().setVisible(true));
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButtonAmbilSemuaData;
    private javax.swing.JButton jButtonEdit;
    private javax.swing.JButton jButtonHapus;
    private javax.swing.JButton jButtonResetIndeks;
    private javax.swing.JButton jButtonTambahkan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JLabel lblStatusIndeks;
    private javax.swing.JList<String> listId;
    private javax.swing.JList<String> listNama;
    private javax.swing.JTextField txtIdEdit;
    private javax.swing.JTextField txtIdHapus;
    private javax.swing.JTextField txtInputNama;
    private javax.swing.JTextField txtInputNama1;
    private javax.swing.JTextField txtInputNama2;
    private javax.swing.JTextField txtNamaEdit;
    // End of variables declaration                   
    
    private void listIdValueChanged() {
        int index = listId.getSelectedIndex();
        if (index != -1) {
            // Samakan sorotan listNama dengan listId agar sinkron
            listNama.setSelectedIndex(index);
            
            String selectedId = listId.getSelectedValue();
            String selectedNama = listNama.getModel().getElementAt(index);
            
            // Isi textfield edit secara otomatis
            txtIdEdit.setText(selectedId);
            txtNamaEdit.setText(selectedNama);
            
            // Isi textfield hapus secara otomatis
            txtIdHapus.setText(selectedId);
            jTextField5.setText(selectedNama); // jTextField5 adalah field nama untuk hapus di kode Anda
        }
    }

    private void listNamaValueChanged() {
        int index = listNama.getSelectedIndex();
        if (index != -1) {
            // Samakan sorotan listId dengan listNama agar sinkron
            listId.setSelectedIndex(index);
            
            String selectedId = listId.getModel().getElementAt(index);
            String selectedNama = listNama.getSelectedValue();
            
            // Isi textfield edit secara otomatis
            txtIdEdit.setText(selectedId);
            txtNamaEdit.setText(selectedNama);
            
            // Isi textfield hapus secara otomatis
            txtIdHapus.setText(selectedId);
            jTextField5.setText(selectedNama);
        }
    }
    
    private void clearFields() {
        txtInputNama.setText("");    // Sesuai variabel: text field input tambah nama
        txtIdEdit.setText("");       // Sesuai variabel: text field ID di baris Edit
        txtNamaEdit.setText("");     // Sesuai variabel: text field Nama di baris Edit
        txtIdHapus.setText("");      // Sesuai variabel: text field ID di baris Hapus
        jTextField5.setText("");     // Sesuai variabel: text field Nama di baris Hapus
    }
    
    private void displayToGUI() {
        // Ambil semua data mahasiswa dari database melalui service
        java.util.List<jdbc.model.Mahasiswa> listMhs = service.getAll();
        
        // Siapkan model kosong untuk menampung data
        javax.swing.DefaultListModel<String> modelId = new javax.swing.DefaultListModel<>();
        javax.swing.DefaultListModel<String> modelNama = new javax.swing.DefaultListModel<>();
        
        // Iterasi masukkan data ke dalam model
        for (jdbc.model.Mahasiswa mhs : listMhs) {
            modelId.addElement(String.valueOf(mhs.getId()));
        
            modelNama.addElement(mhs.getNama());
        }
        
        // Set model tersebut ke komponen JList di layar GUI
        listId.setModel(modelId);
        listNama.setModel(modelNama);
    }



}